baseurl = "http://www.redox-os.org/"
title = "Redox - Your Next(Gen) OS"
DefaultContentLanguage = "en"

[languages.en]
  weight = 0
  languageName = "English"
  languageCode = "en-us"
[[languages.en.menu.main]]
  weight = 0
  name = "Documentation"
  url = "/docs/"
[[languages.en.menu.main]]
  weight = 1
  name = "News"
  url = "/news/"
[[languages.en.menu.main]]
  weight = 2
  name = "Screenshots"
  url = "/screens/"
[[languages.en.menu.main]]
  weight = 3
  name = "Donate"
  url = "/donate/"
[[languages.en.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.en.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.en.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.zh]
  weight = 1
  languageName = "中文"
  languageCode = "zh-cn"
[[languages.zh.menu.main]]
  weight = 0
  name = "文档"
  url = "/docs/"
[[languages.zh.menu.main]]
  weight = 1
  name = "新闻"
  url = "/news/"
[[languages.zh.menu.main]]
  weight = 2
  name = "截图"
  url = "/screens/"
[[languages.zh.menu.main]]
  weight = 3
  name = "捐赠"
  url = "/donate/"
[[languages.zh.menu.main]]
  weight = 4
  name = "论坛"
  url = "https://discourse.redox-os.org/"
[[languages.zh.menu.main]]
  weight = 5
  name = "代码库"
  url = "https://github.com/redox-os/redox"
[[languages.zh.menu.main]]
  weight = 6
  name = "推特"
  url = "https://twitter.com/redox_os"

[languages.es]
  weight = 2
  languageName = "Español"
  languageCode = "es-es"
[[languages.es.menu.main]]
  weight = 0
  name = "Documentación"
  url = "/docs/"
[[languages.es.menu.main]]
  weight = 1
  name = "Novedades"
  url = "/news/"
[[languages.es.menu.main]]
  weight = 2
  name = "Capturas"
  url = "/screens/"
[[languages.es.menu.main]]
  weight = 3
  name = "Donar"
  url = "/donate/"
[[languages.es.menu.main]]
  weight = 4
  name = "Foro"
  url = "https://discourse.redox-os.org/"
[[languages.es.menu.main]]
  weight = 5
  name = "Repositorio"
  url = "https://github.com/redox-os/redox"
[[languages.es.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.fr]
  weight = 3
  languageName = "Français"
  languageCode = "fr-fr"
[[languages.fr.menu.main]]
  weight = 0
  name = "Documentation"
  url = "/docs/"
[[languages.fr.menu.main]]
  weight = 1
  name = "Nouvelles"
  url = "/news/"
[[languages.fr.menu.main]]
  weight = 2
  name = "Captures d'écran"
  url = "/screens/"
[[languages.fr.menu.main]]
  weight = 3
  name = "Donner"
  url = "/donate/"
[[languages.fr.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.fr.menu.main]]
  weight = 5
  name = "Répertoire"
  url = "https://github.com/redox-os/redox"
[[languages.fr.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.de]
  weight = 4
  languageName = "Deutsch"
  languageCode = "de-de"
[[languages.de.menu.main]]
  weight = 0
  name = "Dokumentation"
  url = "/docs/"
[[languages.de.menu.main]]
  weight = 1
  name = "Neuigkeiten"
  url = "/news/"
[[languages.de.menu.main]]
  weight = 2
  name = "Bildschirmfotos"
  url = "/screens/"
[[languages.de.menu.main]]
  weight = 3
  name = "Spenden"
  url = "/donate/"
[[languages.de.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.de.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.de.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.tr]
  weight = 5
  languageName = "Türkçe"
  languageCode = "tr-tr"
[[languages.tr.menu.main]]
  weight = 0
  name = "Belgeler"
  url = "/docs/"
[[languages.tr.menu.main]]
  weight = 1
  name = "Haberler"
  url = "/news/"
[[languages.tr.menu.main]]
  weight = 2
  name = "Ekran Görüntüleri"
  url = "/screens/"
[[languages.tr.menu.main]]
  weight = 3
  name = "Bağış"
  url = "/donate/"
[[languages.tr.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.tr.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.tr.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.sv]
  weight = 6
  languageName = "Svenska"
  languageCode = "sv-se"
[[languages.sv.menu.main]]
  weight = 0
  name = "Dokumentation"
  url = "/docs/"
[[languages.sv.menu.main]]
  weight = 1
  name = "Nyheter"
  url = "/news/"
[[languages.sv.menu.main]]
  weight = 2
  name = "Skärmbilder"
  url = "/screens/"
[[languages.sv.menu.main]]
  weight = 3
  name = "Donera"
  url = "/donate/"
[[languages.sv.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.sv.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.sv.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.nl]
  weight = 7
  languageName = "Nederlands"
  languageCode = "nl-NL"
[[languages.nl.menu.main]]
  weight = 0
  name = "Documentatie"
  url = "/docs/"
[[languages.nl.menu.main]]
  weight = 1
  name = "Nieuws"
  url = "/news/"
[[languages.nl.menu.main]]
  weight = 2
  name = "Screenshots"
  url = "/screens/"
[[languages.nl.menu.main]]
  weight = 3
  name = "Doneer"
  url = "/donate/"
[[languages.nl.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.nl.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.nl.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.da]
  weight = 8
  languageName = "Dansk"
  languageCode = "da-dk"
[[languages.da.menu.main]]
  weight = 0
  name = "Dokumentation"
  url = "/docs/"
[[languages.da.menu.main]]
  weight = 1
  name = "Nyheder"
  url = "/news/"
[[languages.da.menu.main]]
  weight = 2
  name = "Skærmbilleder"
  url = "/screens/"
[[languages.da.menu.main]]
  weight = 3
  name = "Doner"
  url = "/donate/"
[[languages.da.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.da.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.da.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.no]
  weight = 9
  languageName = "Norsk"
  languageCode = "nb-no"
[[languages.no.menu.main]]
  weight = 0
  name = "Dokumentasjon"
  url = "/docs/"
[[languages.no.menu.main]]
  weight = 1
  name = "Nyheter"
  url = "/news/"
[[languages.no.menu.main]]
  weight = 2
  name = "Skjermbilder"
  url = "/screens/"
[[languages.no.menu.main]]
  weight = 3
  name = "Donere"
  url = "/donate/"
[[languages.no.menu.main]]
  weight = 4
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.no.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.no.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.cz]
  weight = 10
  languageName = "Čeština"
  languageCode = "cz"
[[languages.cz.menu.main]]
  weight = 0
  name = "Dokumentace"
  url = "/docs/"
[[languages.cz.menu.main]]
  weight = 1
  name = "Novinky"
  url = "../news/"
[[languages.cz.menu.main]]
  weight = 2
  name = "Jak vypadá?"
  url = "/screens/"
[[languages.cz.menu.main]]
  weight = 3
  name = "Darovat"
  url = "/donate/"
[[languages.cz.menu.main]]
  weight = 4
  name = "Fórum"
  url = "https://discourse.redox-os.org/"
[[languages.cz.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.cz.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"

[languages.eo]
  weight = 11
  languageName = "Esperanto"
  languageCode = "eo"
[[languages.eo.menu.main]]
  weight = 0
  name = "Dokumentado"
  url = "/docs/"
[[languages.eo.menu.main]]
  weight = 1
  name = "Novaĵoj"
  url = "/news/"
[[languages.eo.menu.main]]
  weight = 2
  name = "Ekrankopioj"
  url = "/screens/"
[[languages.eo.menu.main]]
  weight = 3
  name = "Donaci"
  url = "/donate/"
[[languages.eo.menu.main]]
  weight = 4
  name = "Forumo"
  url = "https://discourse.redox-os.org/"
[[languages.eo.menu.main]]
  weight = 5
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[languages.eo.menu.main]]
  weight = 6
  name = "Twitter"
  url = "https://twitter.com/redox_os"
