baseurl = "http://www.redox-os.org/"
title = "Redox - Your Next(Gen) OS"
DefaultContentLanguage = "en"

[languages.en]
  weight = 0
  languageName = "English"
  languageCode = "en-us"
[[languages.en.menu.main]]
  weight = 0
  name = "Documentation"
  url = "/docs/"
[[languages.en.menu.main]]
  weight = 1
  name = "News"
  url = "/news/"
[[languages.en.menu.main]]
  weight = 2
  name = "Screenshots"
  url = "/screens/"
[[languages.en.menu.main]]
  weight = 3
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.en.menu.main]]
  weight = 4
  name = "GitHub"
  url = "https://github.com/redox-os/redox"

[languages.zh]
  weight = 1
  languageName = "中文"
  languageCode = "zh-cn"
[[languages.zh.menu.main]]
  weight = 0
  name = "文档"
  url = "/docs/"
[[languages.zh.menu.main]]
  weight = 1
  name = "新闻"
  url = "../news/"
[[languages.zh.menu.main]]
  weight = 2
  name = "截图"
  url = "/screens/"
[[languages.zh.menu.main]]
  weight = 3
  name = "论坛"
  url = "https://discourse.redox-os.org/"
[[languages.zh.menu.main]]
  weight = 4
  name = "代码库"
  url = "https://github.com/redox-os/redox"

[languages.es]
  weight = 2
  languageName = "Español"
  languageCode = "es-es"
[[languages.es.menu.main]]
  weight = 0
  name = "Documentación"
  url = "/docs/"
[[languages.es.menu.main]]
  weight = 1
  name = "Novedades"
  url = "../news/"
[[languages.es.menu.main]]
  weight = 2
  name = "Capturas"
  url = "/screens/"
[[languages.es.menu.main]]
  weight = 3
  name = "Foro"
  url = "https://discourse.redox-os.org/"
[[languages.es.menu.main]]
  weight = 4
  name = "Repositorio"
  url = "https://github.com/redox-os/redox"

[languages.fr]
  weight = 3
  languageName = "Français"
  languageCode = "fr-fr"
[[languages.fr.menu.main]]
  weight = 0
  name = "Documentation"
  url = "/docs/"
[[languages.fr.menu.main]]
  weight = 1
  name = "Nouvelles"
  url = "../news/"
[[languages.fr.menu.main]]
  weight = 2
  name = "Captures d'écran"
  url = "/screens/"
[[languages.fr.menu.main]]
  weight = 3
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[languages.fr.menu.main]]
  weight = 4
  name = "Répertoire"
  url = "https://github.com/redox-os/redox"
